language: objective-c
osx_image: xcode10.1
script:
  - xcodebuild -project RHPlaceholder/RHPlaceholder.xcodeproj -target RHPlaceholder -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=11'